# Ruby version
AllCops:
  TargetRubyVersion: 2.5

# Metrics
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

# Naming
Naming/PredicateName:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false

# Layout
Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation
Layout/CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/IndentHash:
  EnforcedStyle: consistent
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  Enabled: false

# Style
Style/NumericPredicate:
  Enabled: true
  EnforcedStyle: comparison
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
Style/IfUnlessModifier:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/SingleLineMethods:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/TrailingCommaInLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/Next:
  Enabled: false
Style/NumericLiterals:
  Enabled: false
Style/MultilineTernaryOperator:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/AsciiComments:
  Enabled: false
Style/BracesAroundHashParameters:
  Enabled: false
Style/EachWithObject:
  Enabled: false
Style/EmptyMethod:
  Enabled: false

# Performance
Performance/Casecmp:
  Enabled: false
