name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Run lint
      run: |
        bundle exec rubocop
    - name: Run tests
      run: |
        bundle exec rake test
